apiVersion: v1
kind: Service
metadata:
  name: goserver-nodeport
spec:
  type: NodePort
  selector:
    app: goserver
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30080
