apiVersion: v1
kind: Secret
metadata:
  name: goserver-secret
type: Opaque
data:
  USER: "Sm9obkRvZQo="  # base64 encoded value of "JohnDoe"
  PASSWORD: "cGFzc3dvcmQxMjMK"  # base64 encoded value of "password123"